sudo: required

language: generic

services:
    - docker

before_install:
    - ls
    - cd indigo
    - docker-compose up -d
    - docker ps -a

script:
    - ls

after_success:
    - if [ "$TRAVIS_BRANCH" == "basic-ros1" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push victoriarobotics/victoriaplatform;
      fi
